### ISSUE TITLE
Feature request: support writing conf in /etc/sshd_config.d

### ISSUE THREAD

**Issue by sprat** [Oefenweb/ansible-ssh-server#9]
I would like this role to support writing the configuration in a file in /etc/sshd_config.d. I can probably create a pull request to support that if you think it's worth merging.

**Comment by tersmitten** [comment]
Can you explain me how you would like to implement this?

**Comment by sprat** [comment]
I don't remember anymore what I was thinking at this time. Maybe to keep the default configuration as-is but generate a file with the configuration values that are provided to the role. But it seems a little bit complicated to implement.

Anyway, I don't use this role (and ansible) anymore, so you can close this issue.
